<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reservation</name>
   <tag></tag>
   <elementGuidId>1ceb7578-0240-453e-a0c8-308ce69a28e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(9) > ul > li:nth-of-type(9) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='left-sidebar']/section/div[2]/ul/li[9]/ul/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b81302a-ed23-4e44-8172-1fa7599409ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/valet</value>
      <webElementGuid>c11b3d7c-95a4-41e7-8c00-e9a7d0ed0f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reservation</value>
      <webElementGuid>d6e29144-6e3b-4a1b-b053-8a73ac614374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-sidebar&quot;)/section[@class=&quot;sidebar&quot;]/div[2]/ul[@class=&quot;sidebar-nav&quot;]/li[9]/ul[1]/li[9]/a[1]</value>
      <webElementGuid>b9393a76-fa05-4c4b-baf3-c97d0f66461a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='left-sidebar']/section/div[2]/ul/li[9]/ul/li[9]/a</value>
      <webElementGuid>5e793bf6-53b5-4d6c-b1d8-0f9a9d73de77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Reservation')])[2]</value>
      <webElementGuid>8ccf9234-e391-49c9-9894-8dcbfdeb0613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Reservation'])[1]/following::a[1]</value>
      <webElementGuid>0af5e16a-3e42-4df6-8e7c-285a0282d1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validation Purchase'])[1]/following::a[2]</value>
      <webElementGuid>a404c46a-e381-4243-a6ff-f9c5f96f6771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Resident'])[1]/preceding::a[1]</value>
      <webElementGuid>e5ddf006-e946-4c0d-a9c2-767649f6b818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Runners'])[1]/preceding::a[1]</value>
      <webElementGuid>ddad5288-d71d-4989-ae47-8556624c0179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reservation']/parent::*</value>
      <webElementGuid>50f58867-f041-46cf-b81e-db885aea7d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/valet')])[11]</value>
      <webElementGuid>eb6ccca7-f5cf-4af2-839e-86e70842f3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/ul/li[9]/a</value>
      <webElementGuid>bded4333-8cd1-4df1-935c-66dada69f22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/valet' and (text() = 'Reservation' or . = 'Reservation')]</value>
      <webElementGuid>8c03ebfa-fb23-43bd-aa53-15abfbbdd846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
