<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_disable</name>
   <tag></tag>
   <elementGuidId>6e6f9442-91db-4f6a-958c-48ff74ecd290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;monthly-pricing-wrap&quot;]/form[${LastFormNumber}]//button[@class=&quot;mpw-update&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
