<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_visibility_checkbox</name>
   <tag></tag>
   <elementGuidId>c8177cd1-a44d-4d63-9063-72b7665ca91e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;monthly-pricing-wrap&quot;]/form[${LastFormNumber}]//input[@id=&quot;rule-visibility&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
