<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_pick_up_runner_value</name>
   <tag></tag>
   <elementGuidId>40bcc457-86bd-480e-9979-409b8ac4bd4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id=&quot;vbd-menu-side&quot;]//span[@class=&quot;text-ellipsis&quot;])[1]/../span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
