<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reservation</name>
   <tag></tag>
   <elementGuidId>58d01af9-350d-40ff-ac57-4923acedf3a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='left-sidebar']/section/div[2]/ul/li[9]/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(9) > ul > li:nth-of-type(9) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55fa7982-0579-4f31-a58e-3c486054aeb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/valet</value>
      <webElementGuid>666c85d4-a71e-44e4-a9eb-5f8a37393f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reservation</value>
      <webElementGuid>c979050a-a784-458a-85e4-b74e5b9a22dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-sidebar&quot;)/section[@class=&quot;sidebar&quot;]/div[2]/ul[@class=&quot;sidebar-nav&quot;]/li[9]/ul[1]/li[9]/a[1]</value>
      <webElementGuid>cb43830e-58e4-4ce5-8fc5-5ebb15252098</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='left-sidebar']/section/div[2]/ul/li[9]/ul/li[9]/a</value>
      <webElementGuid>2429e0b8-176e-4380-87c6-6947a9c1545b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Reservation')])[2]</value>
      <webElementGuid>a8228834-e033-42e8-87a7-a9978c6612d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Reservation'])[1]/following::a[1]</value>
      <webElementGuid>173dc50c-9c27-421e-86ce-304acbea461d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validation Purchase'])[1]/following::a[2]</value>
      <webElementGuid>47901faa-85bd-49f4-b15e-ef5d4f100fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Resident'])[1]/preceding::a[1]</value>
      <webElementGuid>afbb4add-c48e-4efb-ad72-fc73255ef30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Runners'])[1]/preceding::a[1]</value>
      <webElementGuid>7c2a5fa2-76ff-4d10-9970-47b6ca64ae96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reservation']/parent::*</value>
      <webElementGuid>77ed6c14-6ff7-4b57-aac4-fab3d869830e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/valet')])[11]</value>
      <webElementGuid>e288fd27-0c0e-4c5c-8371-b41c81056ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/ul/li[9]/a</value>
      <webElementGuid>1847ed88-1c9c-498a-8d4b-6079e5934ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/valet' and (text() = 'Reservation' or . = 'Reservation')]</value>
      <webElementGuid>1825cc29-e35d-4cc7-b5e0-34cd575784c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
