<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Add Damages_vd-sideViewLeft</name>
   <tag></tag>
   <elementGuidId>5a42dda0-c601-4eb1-b310-8942eca4addc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='vd-sideViewLeft']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vd-sideViewLeft</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>eb23c43e-ed8f-457f-964a-c53eaafbb060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vd-sideViewLeft</value>
      <webElementGuid>a883180c-8d4b-4031-a044-86fc876d439f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>ef8c621e-59bf-4ed8-af7e-b6c095db64c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>77</value>
      <webElementGuid>fe478ebf-cc49-469f-974f-1495f56efe8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vd-sideViewLeft&quot;)</value>
      <webElementGuid>7f5fc5fd-9ed4-4e63-9be7-3f2fe27f1929</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='vd-sideViewLeft']</value>
      <webElementGuid>f845d194-2537-4708-9618-8cec78edd462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-inner']/div/div[2]/div/div/div[3]/div[2]/canvas</value>
      <webElementGuid>3a2194c6-2361-4acb-a2fc-76974ffdaa90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>e6d4e135-9e81-4198-8fc4-1c51ee8c35c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'vd-sideViewLeft']</value>
      <webElementGuid>0d12d3c3-e3e8-43f5-9bdc-7f6d11401014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
