<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_0_valet-add-reservation fa fa-plus-circle</name>
   <tag></tag>
   <elementGuidId>998a2e23-60d0-474f-89f5-06a47f72e5de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-inner']/div/div[2]/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.valet-add-reservation.fa.fa-plus-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3a5c299f-2089-492a-91bd-de1d54ca294a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valet-add-reservation fa fa-plus-circle</value>
      <webElementGuid>54a23adb-102f-48f5-9aba-f51155958a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-inner&quot;)/div[@class=&quot;valet-central valet-wrapper-desktop valet-tabs&quot;]/div[2]/div[@class=&quot;valet-wrapper valet-wrapper-desktop valet-visitor-main&quot;]/div[1]/i[@class=&quot;valet-add-reservation fa fa-plus-circle&quot;]</value>
      <webElementGuid>2dc51f7c-2da1-4a82-bece-99ed7a330350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-inner']/div/div[2]/div/div/i</value>
      <webElementGuid>23017ba8-39ef-42b6-8f4f-71658c515a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/i</value>
      <webElementGuid>be63a2a2-5a83-4e83-b14d-b056e609d0cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
