<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_room_number_Guest_In</name>
   <tag></tag>
   <elementGuidId>2ca792cb-0f9a-4b17-b939-ea0d271e7a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[text()=&quot;${Section}&quot;]/../..//child::div[text()=&quot;${LastName}&quot;])[1]/../div[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
