<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_each_mandatory_field</name>
   <tag></tag>
   <elementGuidId>7aef03c3-2a1d-43a8-8d44-956bc26fcdb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//i[text()=&quot;*&quot;]/../../div[@class=&quot;error-msg&quot;])[${count}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
