<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_hide_or_shoe_check</name>
   <tag></tag>
   <elementGuidId>d23cb5cd-a448-4b70-b658-5aafe195e579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text()[2],&quot;${Section}&quot;)]/..//span[contains(text(),&quot;${Description}&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
