<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_location_on_card</name>
   <tag></tag>
   <elementGuidId>71c4a949-3340-490c-89a4-d8467ef93968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),&quot;${Section}&quot;)]/../../div/div/div[text()=&quot;${LicensePlateNo}&quot;]//following-sibling::div[@class=&quot;vs-car-location&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
