<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>reservation_by_license_plate_no_Out</name>
   <tag></tag>
   <elementGuidId>31cc7421-a228-4bd1-85ad-88ae8b5bf037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[text()=&quot;Out&quot;]/../..//child::div[text()=&quot;${LicensePlateNo}&quot;])[1]/..</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
